// lib/mock.ts
// Реалістичні дані для розробки поки не підключено Supabase

import type { User, LearningRequest, Pair, Session, Message } from '@/types'

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Марія',
    country: 'IT',
    timezone: 'Europe/Rome',
    bio: 'Живу в Мілані три роки. Англійська потрібна на роботі щодня.',
    gratitude_message: 'Я безмежно вдячна кожному хто готовий витратити свій час на мене.',
    can_teach: ['Готування', 'Італійська'],
    wants_to_learn: ['Англійська'],
    languages: ['uk', 'it'],
    total_hours: 11,
    total_sessions: 8,
    streak_weeks: 7,
    created_at: '2026-04-24T10:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Андрій',
    country: 'NL',
    timezone: 'Europe/Amsterdam',
    bio: 'Переїжджаю до Відня через 4 місяці — дуже мотивований говорити до приїзду.',
    gratitude_message: 'Буду дуже вдячний за будь-яку допомогу з німецькою.',
    can_teach: ['Англійська', 'Нідерландська'],
    wants_to_learn: ['Німецька'],
    languages: ['uk', 'en'],
    total_hours: 3,
    total_sessions: 3,
    streak_weeks: 3,
    created_at: '2026-05-15T10:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Наталя',
    country: 'CA',
    timezone: 'America/Toronto',
    bio: 'Виросла в російськомовній родині — зараз хочу говорити рідною мовою.',
    gratitude_message: 'Для мене це не просто урок — це повернення до себе.',
    can_teach: ['Французька', 'Англійська'],
    wants_to_learn: ['Українська'],
    languages: ['ru', 'en', 'fr'],
    total_hours: 6,
    total_sessions: 5,
    streak_weeks: 5,
    created_at: '2026-04-01T10:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Дмитро',
    country: 'US',
    timezone: 'America/New_York',
    bio: 'Хочу автоматизувати роботу і може колись змінити сферу.',
    gratitude_message: 'Англійська вільно — можу допомогти у відповідь.',
    can_teach: ['Англійська'],
    wants_to_learn: ['Python'],
    languages: ['uk', 'en'],
    total_hours: 0,
    total_sessions: 0,
    streak_weeks: 0,
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'user-5',
    name: 'Юлія',
    country: 'GB',
    timezone: 'Europe/London',
    bio: 'Живу за кордоном 3 роки і дуже сумую за домашньою їжею.',
    gratitude_message: 'Хочу навчитись борщу, вареникам, голубцям. Викладаю йогу — можу у відповідь.',
    can_teach: ['Йога', 'Англійська'],
    wants_to_learn: ['Готування'],
    languages: ['uk', 'en'],
    total_hours: 0,
    total_sessions: 0,
    streak_weeks: 0,
    created_at: '2026-06-05T10:00:00Z',
  },
  {
    id: 'user-6',
    name: 'Олена',
    country: 'DE',
    timezone: 'Europe/Berlin',
    bio: 'Вже кілька років відкладаю — нарешті хочу почати грати на гітарі.',
    gratitude_message: 'Малюю акварель і можу навчити у відповідь.',
    can_teach: ['Малювання'],
    wants_to_learn: ['Гітара'],
    languages: ['uk', 'de'],
    total_hours: 0,
    total_sessions: 0,
    streak_weeks: 0,
    created_at: '2026-06-08T10:00:00Z',
  },
]

export const MOCK_REQUESTS: LearningRequest[] = [
  {
    id: 'req-1',
    user_id: 'user-1',
    user: MOCK_USERS[0],
    subject: 'Англійська',
    level: 'beginner',
    text: 'Хочу вивчити англійську мову. Буду безмежно вдячна кожному хто готовий витратити свій час — для мене це дуже багато значить.',
    frequency: 'once_week',
    age: 24,
    status: 'open',
    created_at: '2026-06-09T10:00:00Z',
  },
  {
    id: 'req-2',
    user_id: 'user-2',
    user: MOCK_USERS[1],
    subject: 'Німецька',
    level: 'beginner',
    text: 'Хочу вивчити німецьку з нуля — переїжджаю до Відня через 4 місяці. Дуже мотивований.',
    frequency: 'twice_week',
    age: 22,
    status: 'open',
    created_at: '2026-06-08T10:00:00Z',
  },
  {
    id: 'req-3',
    user_id: 'user-3',
    user: MOCK_USERS[2],
    subject: 'Українська',
    level: 'elementary',
    text: 'Хочу повернути українську — виросла в російськомовній родині. Потрібен живий розмовний партнер.',
    frequency: 'flexible',
    age: 38,
    status: 'open',
    created_at: '2026-06-07T10:00:00Z',
  },
  {
    id: 'req-4',
    user_id: 'user-4',
    user: MOCK_USERS[3],
    subject: 'Python',
    level: 'beginner',
    text: 'Хочу навчитись програмувати на Python. Є базове розуміння логіки але нічого не писав.',
    frequency: 'once_week',
    age: 27,
    status: 'open',
    created_at: '2026-06-06T10:00:00Z',
  },
  {
    id: 'req-5',
    user_id: 'user-5',
    user: MOCK_USERS[4],
    subject: 'Готування',
    level: 'beginner',
    text: 'Мрію навчитись готувати борщ, вареники, голубці. Три роки без домашньої їжі — це складно.',
    frequency: 'once_week',
    age: 29,
    status: 'open',
    created_at: '2026-06-05T10:00:00Z',
  },
  {
    id: 'req-6',
    user_id: 'user-6',
    user: MOCK_USERS[5],
    subject: 'Гітара',
    level: 'beginner',
    text: 'Мрію навчитись грати на гітарі. Вже кілька років відкладаю — нарешті хочу почати. З нуля.',
    frequency: 'flexible',
    age: 31,
    status: 'open',
    created_at: '2026-06-04T10:00:00Z',
  },
]

export const MOCK_PAIRS: Pair[] = [
  {
    id: 'pair-1',
    mentor_id: 'current-user',
    learner_id: 'user-1',
    request_id: 'req-1',
    learner: MOCK_USERS[0],
    subject: 'Англійська',
    whereby_room_url: 'https://whereby.com/retech-dev-pair-1',
    status: 'active',
    total_hours: 11,
    sessions_count: 8,
    created_at: '2026-04-24T10:00:00Z',
  },
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    pair_id: 'pair-1',
    sender_id: 'user-1',
    sender: MOCK_USERS[0],
    text: 'Привіт! Дякую що відгукнувся 🙂 Коли тобі зручно провести першу зустріч?',
    created_at: '2026-04-24T18:00:00Z',
  },
  {
    id: 'msg-2',
    pair_id: 'pair-1',
    sender_id: 'current-user',
    text: 'Привіт! Можу у вівторок або четвер ввечері — як тобі?',
    created_at: '2026-04-24T18:05:00Z',
  },
  {
    id: 'msg-3',
    pair_id: 'pair-1',
    sender_id: 'user-1',
    sender: MOCK_USERS[0],
    text: 'Вівторок ідеально! О 19:00 підійде?',
    created_at: '2026-04-24T18:10:00Z',
  },
]

export const MOCK_SESSIONS: Session[] = [
  {
    id: 'session-1',
    pair_id: 'pair-1',
    scheduled_at: '2026-06-15T19:00:00Z',
    duration_min: 60,
    status: 'scheduled',
    created_at: '2026-06-10T10:00:00Z',
  },
]

// ─── Поточний mock користувач (замінюється Supabase Auth) ────────────────────
export const MOCK_CURRENT_USER: User = {
  id: 'current-user',
  name: 'Олексій',
  country: 'DE',
  timezone: 'Europe/Berlin',
  bio: 'Живу в Охтрупі. Вивчаю німецьку. Допомагаю з англійською.',
  can_teach: ['Англійська', 'Python'],
  wants_to_learn: ['Німецька'],
  languages: ['uk', 'en'],
  total_hours: 11,
  total_sessions: 8,
  streak_weeks: 7,
  created_at: '2026-04-01T10:00:00Z',
}
